### ISSUE TITLE
local cache `~/.cdist/cache/<md5 hash>`

### ISSUE THREAD

**Issue by tom-ee** [ungleich/cdist#631]
We now have documentation for `Local cache overview` thanks to @darko-poljak :)

The one thing I'm wondering about is the md5-hash of the hostname: It buys nothing for uniqueness. The allowed characters in a hostname are fine for naming a directory.

Would it be reasonable to change the cache path to `~/.cdist/cache/${__target_hostname}` instead of `~/.cdist/cache/$(echo -n ${__target_hostname} | md5sum)`?

I havn't checked or tested if any normalization of the hostname (it seems that `__target_hostname` is used) is done -- apologies for the lazyness. That's the only reason for making the hunt for the correct directory harder by using the md5 hash I could come up with.

**Comment by darko-poljak** [comment]
@tom-ee You can change host cache directory name, see CACHE PATH PATTERN FORMAT in cdist man page. This is also mentioned in local cache overview docs chapter.

It was changed from target host name because cdist can be used with custom remote_exec/copy and target host can be anything, not only valid hostnames. For example, for custom remote commands that work wich chroot target host can be a directory path.
